# DNN Model Configuration for AQI Prediction

# Data Configuration
data:
  input_file: "bangalore_historical_aqi_weather.csv"
  features: ["temperature_2m", "relative_humidity_2m"]
  target: "calculated_aqi"
  test_split: 0.2
  validation_split: 0.2
  random_state: 42
  scale_features: true
  scale_target: true

# Model Architecture
model:
  layers:
    - units: 128
      activation: "relu"
      dropout: 0.3
      batch_norm: true
    - units: 256
      activation: "relu"
      dropout: 0.3
      batch_norm: true
    - units: 512
      activation: "relu"
      dropout: 0.3
      batch_norm: true
    - units: 256
      activation: "relu"
      dropout: 0.3
      batch_norm: true
    - units: 128
      activation: "relu"
      dropout: 0.2
      batch_norm: true
    - units: 64
      activation: "relu"
      dropout: 0.2
      batch_norm: true
  output:
    units: 1
    activation: "linear"

# Training Configuration
training:
  optimizer:
    type: "adam"
    learning_rate: 0.001
  loss: "mse"
  metrics: ["mae", "mse"]
  epochs: 100
  batch_size: 32
  verbose: 1

# Callbacks
callbacks:
  early_stopping:
    enabled: false
    monitor: "val_loss"
    patience: 15
    restore_best_weights: true
    verbose: 1

  reduce_lr:
    enabled: true
    monitor: "val_loss"
    factor: 0.5
    patience: 5
    min_lr: 0.00001
    verbose: 1

# Output Configuration
output:
  save_model: true
  model_path: "aqi_dnn_model.keras"
  save_scalers: true
  scaler_x_path: "scaler_X.pkl"
  scaler_y_path: "scaler_y.pkl"
  save_predictions: true
  predictions_path: "aqi_predictions.csv"
  save_plots: true
  plots_path: "aqi_dnn_results.png"
  plot_dpi: 100

# Evaluation Settings
evaluation:
  calculate_mape: true
  show_sample_predictions: true
  test_cases:
    - temperature: 25.0
      humidity: 60.0
      description: "Moderate temp and humidity"
    - temperature: 35.0
      humidity: 40.0
      description: "High temp, low humidity"
    - temperature: 20.0
      humidity: 80.0
      description: "Low temp, high humidity"
    - temperature: 30.0
      humidity: 50.0
      description: "High temp, moderate humidity"